version: '3.9'

services:
  universitly:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: universitly
    ports:
      - "${DJANGO_PORT}:8000"
    command: sh /entrypoint.sh
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - ..:/app/
