version: "3.9"

services:
  universitly:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: universitly
    ports:
      - "${DJANGO_PORT}:8000"
    command: sh /entrypoint.sh
    env_file:
      - ../.env
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ..:/app/

  celery_worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: universitly_celery_worker
    command: celery -A core.config.settings worker --loglevel=info

    env_file:
      - ../.env
    depends_on:
      - universitly
      - rabbitmq
    volumes:
      - ..:/app/

  celery_beat:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: universitly_celery_beat
    command: celery -A core.config.settings beat --loglevel=info
    env_file:
      - ../.env
    depends_on:
      - universitly
      - rabbitmq

