version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: universitly_db
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - universitly_postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  redis:
    image: redis:latest
    container_name: universitly_redis
    ports:
      - '6379:6379'
    volumes:
      - universitly_redis_data:/data
    env_file:
      - ../.env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: universitly_rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - ../.env

volumes:
  universitly_postgres_data:
  universitly_redis_data:
