# Generated by Django 5.1.6 on 2025-02-18 15:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='Teachers'),
        ),
        migrations.AddField(
            model_name='institution',
            name='admins',
            field=models.ManyToManyField(related_name='administrated_institutions', to=settings.AUTH_USER_MODEL, verbose_name='Admins'),
        ),
        migrations.AddField(
            model_name='institution',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_institutions', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='education.institution', verbose_name='Related institution'),
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='education.course', verbose_name='Related course'),
        ),
        migrations.AddField(
            model_name='sectionfile',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='education.section', verbose_name='Related section'),
        ),
        migrations.AddField(
            model_name='sectionhomework',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='education.section', verbose_name='Related section'),
        ),
        migrations.AddField(
            model_name='sectiontest',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='education.section', verbose_name='Related section'),
        ),
        migrations.AddConstraint(
            model_name='sectionhomework',
            constraint=models.CheckConstraint(condition=models.Q(('deadline__gt', datetime.datetime(2025, 2, 18, 15, 32, 19, 479158, tzinfo=datetime.timezone.utc))), name='deadline_gt_now'),
        ),
        migrations.AddConstraint(
            model_name='sectiontest',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gte', models.F('passing_score'))), name='max_score_gte_passing_score'),
        ),
        migrations.AddConstraint(
            model_name='sectiontest',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__gte', datetime.datetime(2025, 2, 18, 15, 32, 19, 480019, tzinfo=datetime.timezone.utc))), name='start_date_gte_now'),
        ),
        migrations.AddConstraint(
            model_name='sectiontest',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='end_date_gt_start_date'),
        ),
    ]
