# Generated by Django 5.1.6 on 2025-02-21 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sectionhomework',
            name='deadline_gt_now',
        ),
        migrations.RemoveConstraint(
            model_name='sectiontest',
            name='start_date_gte_now',
        ),
        migrations.AlterField(
            model_name='institution',
            name='icon',
            field=models.ImageField(default='institutions/default.png', upload_to='institutions/', verbose_name='Icon'),
        ),
        migrations.AddConstraint(
            model_name='sectionhomework',
            constraint=models.CheckConstraint(condition=models.Q(('deadline__gt', datetime.datetime(2025, 2, 21, 14, 2, 0, 327674, tzinfo=datetime.timezone.utc))), name='deadline_gt_now'),
        ),
        migrations.AddConstraint(
            model_name='sectiontest',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__gte', datetime.datetime(2025, 2, 21, 14, 2, 0, 328567, tzinfo=datetime.timezone.utc))), name='start_date_gte_now'),
        ),
    ]
