# Generated by Django 5.1.6 on 2025-02-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('CI', 'Creating institution'), ('UI', 'Updating institution'), ('DI', 'Deleting institution'), ('M', 'Marketing')], unique=True, verbose_name='Type')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('plain_text', models.TextField(verbose_name='Plain text')),
                ('html', models.TextField(verbose_name='HTML')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
