# Generated by Django 5.1.6 on 2025-02-18 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('type', models.CharField(choices=[('SCHOOL', 'School'), ('UNI', 'University'), ('OTHER', 'Other')], default='OTHER', verbose_name='Type')),
                ('icon', models.ImageField(upload_to='institutions/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('type', models.CharField(choices=[('L', 'Lecture'), ('HW', 'Homework'), ('T', 'Test')], default='L', verbose_name='Type')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='SectionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='section_files/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Section file',
                'verbose_name_plural': 'Section files',
            },
        ),
        migrations.CreateModel(
            name='SectionHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('deadline', models.DateTimeField(blank=True, verbose_name='Deadline')),
            ],
            options={
                'verbose_name': 'Section homework',
                'verbose_name_plural': 'Section homeworks',
            },
        ),
        migrations.CreateModel(
            name='SectionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('questions', models.JSONField(verbose_name='Questions')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='Max score')),
                ('passing_score', models.PositiveIntegerField(default=50, verbose_name='Passing score')),
                ('max_attempts', models.PositiveIntegerField(default=1, verbose_name='Attempts')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
            ],
            options={
                'verbose_name': 'Section test',
                'verbose_name_plural': 'Section tests',
            },
        ),
    ]
